TEST_INPUT = [
    {
        'name': 'AA',
        'date': '2010-01-04',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 100,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-05',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 10.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-06',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-07',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 100,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-08',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-09',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-10',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 100,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-11',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-12',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-13',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 100,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-14',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 15.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-15',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 17.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-16',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 20.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
    {
        'name': 'AA',
        'date': '2010-01-17',
        'open_price': 10.0,
        'close_price': 10.0,
        'high_price': 17.0,
        'low_price': 5.0,
        'volume': 110,
        'market': 'NYSE',
    },
]
