version: '3.5'

services:
  db:
    container_name: db
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/postgresql/data

  # NOTE: Test DB doesn't require a persistent volume, since the data isn't supposed and should'nt be persisted
  test-db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=ph_tests

    ports:
      - "15432:5432"

  pipeline:
    platform: linux/amd64
    build: ./pipeline
    command: tail -F anything
    depends_on:
      - db
    environment: &db_environment
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: ${POSTGRES_DB_NAME:-postgres}

  # api:
  #   build: ./api
  #   # command: tail -F anything
  #   depends_on:
  #     - db
  #   environment:
  #     <<: *db_environment

volumes:
  db-volume:
    external: true
