name: tests
on:
  push:
    paths:
      - "api/**"
      - "docker-compose.yaml"
jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create prerequisites
        run: docker volume create db-volume
      - name: Build test image
        run: 	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build api-tests-ci
      - name: Run tests
        run: 	COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose run api-tests-ci
      - name: Debug
        run: docker ps
      - name: Shutdown
        run: docker-compose down

  pre-commit-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
